name: AI Code Review Codium PR-agent OpenAi api (via Tailscale)

on:
  workflow_call: 
    inputs:
      pr_number:
        description: 'Input pull request number'
        required: true
        type: string
      api:
        description: 'Input api'
        required: true
        type: string  
      model_name:
        description: 'Select model'
        required: true
        default: 'qwen2.5-coder:14b'
        type: string  
      language:
        description: 'Select response language'
        required: true
        default: 'English'
        type: string  
  
jobs:  
          
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get git diff
        id: diff_step
        run: |
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          
          BASE_BRANCH="${{ github.base_ref }}"
          if [ -z "$BASE_BRANCH" ]; then
            BASE_BRANCH=$DEFAULT_BRANCH
          fi
          
          echo "Base branch is determined as: $BASE_BRANCH"
          
          git fetch origin $BASE_BRANCH --depth=100
          
          git diff origin/$BASE_BRANCH HEAD -- . ':(exclude)*.lock' > diff.txt
          
          if [ -s diff.txt ]; then
            echo "has_diff=true" >> $GITHUB_OUTPUT
            echo "Changes found."
          else
            echo "has_diff=false" >> $GITHUB_OUTPUT
            echo "No changes detected."
          fi
          
      - name: Prepare API
        id: get_api_step
        run: |
          if [ "${{ inputs.api }}" = "OpenRouter" ]; then 
            val="${{ secrets.OPENROUTER_ENDPOINT }}"
          elif [ "${{ inputs.api }}" = "Llama" ]; then
            val="${{ secrets.LLAMA_ENDPOINT }}"
            
            gh workflow run llama-check-model.yaml \
              --repo innasolp/GithubActions \
              --ref main \
              -f model_name="${{ inputs.model_name }}"
          fi
          
          echo "API_URL=$val" >> $GITHUB_ENV
          echo "Selected API: $val"
        env:
          GH_TOKEN: ${{ secrets.REPO_ACTION_TOKEN }}

      - name: Connect to Tailscale
        if: inputs.api == 'Llama'
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci    
          
      - name: PR Agent - Description & Changes
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/github/workspace \
            -w /app \
            -e GITHUB__USER_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e CONFIG__MODEL="openai/${{ inputs.model_name }}" \
            -e CONFIG__AI_TIMEOUT="1200" \
            -e CONFIG__CUSTOM_MODEL_MAX_TOKENS="4000" \
            -e OPENAI__API_BASE=$API_URL \
             # Запрещаем контейнеру использовать скрытые прокси GitHub для сети Tailscale:
            -e HTTP_PROXY="" \
            -e HTTPS_PROXY="" \
            -e http_proxy="" \
            -e https_proxy="" \
            -e NO_PROXY="localhost,127.0.0.1,100.*" \
            -e no_proxy="localhost,127.0.0.1,100.*" \
             # Полностью отключаем фоллбэк на сервера OpenAI:
            -e CONFIG__FALLBACK_MODELS="[]" \
            -e OPENAI__FALLBACK_MODELS="[]" \
            -e LITELM__FALLBACK_MODELS="[]" \
            codiumai/pr-agent:latest \
            --pr_url="${{ github.server_url }}/${{ github.repository }}/pull/${{ inputs.pr_number }}" \
            ask "In ${{ inputs.language }}, provide a short summary of the main changes in this PR and describe what it does."

       
      - name: PR Agent - Bug Analysis
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/github/workspace \
            -w /app \
            -e GITHUB__USER_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e CONFIG__MODEL="openai/${{ inputs.model_name }}" \
            -e CONFIG__AI_TIMEOUT="1200" \
            -e CONFIG__CUSTOM_MODEL_MAX_TOKENS="4000" \
            -e OPENAI__API_BASE=$API_URL \
             # Запрещаем контейнеру использовать скрытые прокси GitHub для сети Tailscale:
            -e HTTP_PROXY="" \
            -e HTTPS_PROXY="" \
            -e http_proxy="" \
            -e https_proxy="" \
            -e NO_PROXY="localhost,127.0.0.1,100.*" \
            -e no_proxy="localhost,127.0.0.1,100.*" \
             # Полностью отключаем фоллбэк на сервера OpenAI:
            -e CONFIG__FALLBACK_MODELS="[]" \
            -e OPENAI__FALLBACK_MODELS="[]" \
            -e LITELM__FALLBACK_MODELS="[]" \
            codiumai/pr-agent:latest \
            --pr_url="${{ github.server_url }}/${{ github.repository }}/pull/${{ inputs.pr_number }}" \
            ask "Point out any critical bugs, logical errors, or performance issues in the code changes. Answer ONLY in ${{ inputs.language }} language."       
