name: AI Code Review Codium PR-agent Ollama (via Tailscale)

on:
  workflow_call: 
    inputs:
      pr_number:
        description: 'Input pull request number'
        required: true
        type: string
      model_name:
        description: 'Select Ollama model'
        required: true
        default: 'qwen2.5-coder:14b'
        type: string
      language:
        description: 'Select response language'
        required: true
        default: 'English'
        type: string
  
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check secrets availability
        run: |
          if [ -z "${{ secrets.TS_OAUTH_CLIENT_ID }}" ]; then
            echo "Secret is EMPTY"
            exit 1
          fi    

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}         
          tags: tag:ci

      - name: Get git diff
        id: diff_step
        run: |
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          
          BASE_BRANCH="${{ github.base_ref }}"
          if [ -z "$BASE_BRANCH" ]; then
            BASE_BRANCH=$DEFAULT_BRANCH
          fi
          
          echo "Base branch is determined as: $BASE_BRANCH"
          
          git fetch origin $BASE_BRANCH --depth=100
          
          git diff origin/$BASE_BRANCH HEAD -- . ':(exclude)*.lock' > diff.txt
          
          if [ -s diff.txt ]; then
            echo "has_diff=true" >> $GITHUB_OUTPUT
            echo "Changes found."
          else
            echo "has_diff=false" >> $GITHUB_OUTPUT
            echo "No changes detected."
          fi

      - name: Network Diagnostic
        run: |
          tailscale status
          curl -v --connect-timeout 10 ${{ secrets.OLLAMA_ENDPOINT }}/api/tags  
          TEST_RESPONSE=$(curl -X POST -d '{"model":${{ github.event.inputs.model_name }},"prompt":"hi", "stream": false}' ${{ secrets.OLLAMA_QWEN_7B_ENDPOINT }}/api/generate)
          echo "Test response on 'hi' from Ollama: $TEST_RESPONSE"

          
      - name: PR Agent - Description & Changes
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/github/workspace \
            -w /app \
            -e GITHUB__USER_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e CONFIG__MODEL="ollama/${{ github.event.inputs.model_name }}" \
            -e CONFIG__AI_TIMEOUT="1200" \
            -e CONFIG__CUSTOM_MODEL_MAX_TOKENS="32000" \
            -e OLLAMA__API_BASE="${{ secrets.OLLAMA_ENDPOINT }}" \
            codiumai/pr-agent:latest \
            --pr_url="${{ github.server_url }}/${{ github.repository }}/pull/${{ inputs.pr_number }}" \
            ask "In ${{ github.event.inputs.language }}, provide a short summary of the main changes in this PR and describe what it does."
     
      - name: PR Agent - Bug Analysis
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/github/workspace \
            -w /app \
            -e GITHUB__USER_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e CONFIG__MODEL="ollama/${{ github.event.inputs.model_name }}" \
            -e CONFIG__AI_TIMEOUT="1200" \
            -e CONFIG__CUSTOM_MODEL_MAX_TOKENS="32000" \
            -e OLLAMA__API_BASE="${{ secrets.OLLAMA_ENDPOINT }}" \
            codiumai/pr-agent:latest \
            --pr_url="${{ github.server_url }}/${{ github.repository }}/pull/${{ inputs.pr_number }}" \
            ask "Point out any critical bugs, logical errors, or performance issues in the code changes. Answer ONLY in ${{ github.event.inputs.language }} language."       
