 name: Push Action to All Repos

 on:
  workflow_dispatch:

 jobs:
  distribute-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4

      - name: Process all repositories
        run: |
          echo "🎉 action!"
