name: Sync Secrets
on:
  push:
    branches:  [ main, develop ]    
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Secrets to Other Repos
        uses: jpoehnelt/secrets-sync-action@v1.10.0 # Check for the latest version
        with:
          # Your custom PAT stored in your source repo secrets
          github_token: ${{ secrets.SYNC_TOKEN }} 
          
          # Repositories to target (space or newline delimited)
          repositories: |
            innasolp/Alchemist
            innasolp/Configuration
            innasolp/WebLoaders
            innasolp/Messages
            innasolp/Import
            innasolp/LogExtensions
            innasolp/DependencyInjection
            innasolp/HttpExtensions
            innasolp/GrpcExtensions
            innasolp/Json.CustomSerialization
            
          # The exact secrets to copy from this repo to the targets
          secrets: |
            LLAMA_ENDPOINT
            OLLAMA_ENDPOINT
            OLLAMA_DOCKER_ENDPOINT
            TS_OAUTH_CLIENT_ID
            TS_OAUTH_SECRET
            REPO_ACTION_TOKEN
        env:
          # You must load the actual values into the environment
          LLAMA_ENDPOINT: ${{ secrets.LLAMA_ENDPOINT }}
          OLLAMA_ENDPOINT: ${{ secrets.OLLAMA_ENDPOINT }}
          OLLAMA_DOCKER_ENDPOINT: ${{ secrets.OLLAMA_DOCKER_ENDPOINT }}
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          REPO_ACTION_TOKEN: ${{ secrets.REPO_ACTION_TOKEN }}
